# Run during the 'gulp build' command
# Overrides these options in _config.yml

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
lsi: true
# Removes the upper limit for posts generated
limit_posts: 0
# Number of posts per index page
paginate: 10

google_analytics: UA-71253711-1

# What should we append to the host url
url: https://ianteda.com
enforce_ssl: ianteda.com
baseurl: ""
